[project]
name = "worlddraft"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "alembic>=1.19.1",
    "asyncpg>=0.31.0",
    "bcrypt>=5.0.0",
    "beautifulsoup4>=4.15.0",
    "email-validator>=2.3.0",
    "fastapi>=0.141.1",
    "greenlet>=3.5.5",
    "joblib>=1.5.3",
    "numpy>=2.4.6",
    "pandas>=3.0.5",
    "passlib>=1.7.4",
    "pydantic>=2.13.4",
    "pydantic-settings>=2.15.0",
    "python-dotenv>=1.2.2",
    "python-jose>=3.5.0",
    "python-levenshtein>=0.27.4",
    "requests>=2.34.2",
    "scikit-learn>=1.9.0",
    "sqlalchemy>=2.0.52",
    "thefuzz>=0.22.1",
    "uvicorn>=0.52.3",
]
