"""add knockout match history and group opponent events

Revision ID: 27a4684ea037
Revises: 51ff44957f8e
Create Date: 2026-08-30 15:15:18.837988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '27a4684ea037'
down_revision: Union[str, Sequence[str], None] = '51ff44957f8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# El tipo "draft_round" ya existe (lo creo draft_sessions.current_round):
# create_type=False para que esta tabla solo lo referencie, no intente
# volver a crearlo (el autogenerate no lo detecta y falla con
# DuplicateObjectError si se deja tal cual).
_draft_round_enum = postgresql.ENUM(
    "GROUP_1",
    "GROUP_2",
    "GROUP_3",
    "ROUND_OF_16",
    "QUARTER_FINAL",
    "SEMI_FINAL",
    "FINAL",
    "ELIMINATED",
    "CHAMPION",
    name="draft_round",
    create_type=False,
)


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table('knockout_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('draft_session_id', sa.Integer(), nullable=False),
    sa.Column('round', _draft_round_enum, nullable=False),
    sa.Column('opponent_country', sa.String(length=100), nullable=False),
    sa.Column('opponent_year', sa.Integer(), nullable=False),
    sa.Column('result', sa.String(length=10), nullable=False),
    sa.Column('home_goals', sa.Integer(), nullable=False),
    sa.Column('away_goals', sa.Integer(), nullable=False),
    sa.Column('penalties_took_place', sa.Boolean(), nullable=False),
    sa.Column('penalties_won', sa.Boolean(), nullable=True),
    sa.Column('advanced', sa.Boolean(), nullable=False),
    sa.Column('events', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['draft_session_id'], ['draft_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # server_default solo para rellenar las filas ya existentes de
    # group_stage_opponents (partidos jugados antes de este cambio, que se
    # quedan sin goleadores conocidos para siempre, pero deben poder seguir
    # leyendose); el modelo (app/db/models.py) ya aplica list() como
    # default en el lado de Python para las filas nuevas, igual que el
    # resto de columnas de esta tabla (ver dece49f4198f).
    op.add_column(
        'group_stage_opponents',
        sa.Column('events', sa.JSON(), nullable=False, server_default=sa.text("'[]'::json")),
    )
    op.alter_column('group_stage_opponents', 'events', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('group_stage_opponents', 'events')
    op.drop_table('knockout_matches')
    # ### end Alembic commands ###
