"""add extra time detail to knockout matches

Revision ID: 28aa03f3bf0d
Revises: 9f9e96206127
Create Date: 2026-08-31 16:52:27.001822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28aa03f3bf0d'
down_revision: Union[str, Sequence[str], None] = '9f9e96206127'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # server_default solo para rellenar las filas ya existentes (partidos
    # jugados antes de este cambio -- todos sin prorroga porque la
    # funcionalidad no existia, asi que 'false' es el valor correcto para
    # ellas, no solo un relleno); el modelo (app/db/models.py) ya aplica
    # False como default en el lado de Python para las filas nuevas.
    op.add_column(
        'knockout_matches',
        sa.Column('went_to_extra_time', sa.Boolean(), nullable=False, server_default=sa.text('false')),
    )
    op.alter_column('knockout_matches', 'went_to_extra_time', server_default=None)
    op.add_column('knockout_matches', sa.Column('extra_time_home_goals', sa.Integer(), nullable=True))
    op.add_column('knockout_matches', sa.Column('extra_time_away_goals', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('knockout_matches', 'extra_time_away_goals')
    op.drop_column('knockout_matches', 'extra_time_home_goals')
    op.drop_column('knockout_matches', 'went_to_extra_time')
    # ### end Alembic commands ###
