"""add group stage rival matches

Revision ID: 51ff44957f8e
Revises: f1fc013ffa35
Create Date: 2026-08-28 18:29:48.041559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51ff44957f8e'
down_revision: Union[str, Sequence[str], None] = 'f1fc013ffa35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_stage_rival_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('draft_session_id', sa.Integer(), nullable=False),
    sa.Column('home_opponent_id', sa.Integer(), nullable=False),
    sa.Column('away_opponent_id', sa.Integer(), nullable=False),
    sa.Column('home_goals', sa.Integer(), nullable=False),
    sa.Column('away_goals', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['away_opponent_id'], ['group_stage_opponents.id'], ),
    sa.ForeignKeyConstraint(['draft_session_id'], ['draft_sessions.id'], ),
    sa.ForeignKeyConstraint(['home_opponent_id'], ['group_stage_opponents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('group_stage_rival_matches')
    # ### end Alembic commands ###
