"""add penalty shootout detail to knockout matches

Revision ID: 9f9e96206127
Revises: 27a4684ea037
Create Date: 2026-08-30 15:31:46.710121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f9e96206127'
down_revision: Union[str, Sequence[str], None] = '27a4684ea037'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('knockout_matches', sa.Column('penalty_home_goals', sa.Integer(), nullable=True))
    op.add_column('knockout_matches', sa.Column('penalty_away_goals', sa.Integer(), nullable=True))
    # server_default solo para rellenar las filas ya existentes (partidos a
    # penaltis jugados antes de este cambio, que se quedan sin el detalle
    # de la tanda para siempre, pero deben poder seguir leyendose); el
    # modelo (app/db/models.py) ya aplica list() como default en el lado de
    # Python para las filas nuevas, igual que el resto de columnas JSON de
    # este cambio (ver 27a4684ea037).
    op.add_column(
        'knockout_matches',
        sa.Column('penalty_kicks', sa.JSON(), nullable=False, server_default=sa.text("'[]'::json")),
    )
    op.alter_column('knockout_matches', 'penalty_kicks', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('knockout_matches', 'penalty_kicks')
    op.drop_column('knockout_matches', 'penalty_away_goals')
    op.drop_column('knockout_matches', 'penalty_home_goals')
    # ### end Alembic commands ###
