"""add unique constraint on player name country year

Revision ID: dcce02d47e2a
Revises: 37537241e311
Create Date: 2026-08-16 16:24:32.931167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcce02d47e2a'
down_revision: Union[str, Sequence[str], None] = '37537241e311'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_player_name_country_year', 'players', ['name', 'country', 'tournament_year'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_player_name_country_year', 'players', type_='unique')
    # ### end Alembic commands ###
