"""add group stage opponents and user group totals

Revision ID: f1fc013ffa35
Revises: 1fc3bbf98252
Create Date: 2026-08-28 13:38:14.171086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1fc013ffa35'
down_revision: Union[str, Sequence[str], None] = '1fc3bbf98252'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table('group_stage_opponents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('draft_session_id', sa.Integer(), nullable=False),
    sa.Column('slot', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('tournament_year', sa.Integer(), nullable=False),
    sa.Column('fifa_points', sa.Float(), nullable=False),
    sa.Column('goals_avg', sa.Float(), nullable=False),
    sa.Column('played', sa.Boolean(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('goals_for', sa.Integer(), nullable=False),
    sa.Column('goals_against', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['draft_session_id'], ['draft_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('draft_session_id', 'slot', name='uq_group_opponent_session_slot')
    )
    # server_default solo para rellenar las filas ya existentes de
    # draft_sessions (sesiones creadas antes de la fase de grupos nueva,
    # que nunca tendran GroupStageOpponent asociado y por tanto se quedan
    # en 0 para siempre); el modelo (app/db/models.py) ya aplica 0 como
    # default en el lado de Python para las filas nuevas, igual que el
    # resto de columnas de esta tabla (ver dece49f4198f).
    op.add_column(
        'draft_sessions', sa.Column('group_points', sa.Integer(), nullable=False, server_default='0')
    )
    op.add_column(
        'draft_sessions', sa.Column('group_goals_for', sa.Integer(), nullable=False, server_default='0')
    )
    op.add_column(
        'draft_sessions', sa.Column('group_goals_against', sa.Integer(), nullable=False, server_default='0')
    )
    op.alter_column('draft_sessions', 'group_points', server_default=None)
    op.alter_column('draft_sessions', 'group_goals_for', server_default=None)
    op.alter_column('draft_sessions', 'group_goals_against', server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('draft_sessions', 'group_goals_against')
    op.drop_column('draft_sessions', 'group_goals_for')
    op.drop_column('draft_sessions', 'group_points')
    op.drop_table('group_stage_opponents')
    # ### end Alembic commands ###
